# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
favicon: /favicon.png


# Site analytics
google_analytics:
cnzz_analytics:
tencent_analytics:
