# Header
menu:
  home: /
  archives: /archives
rss: /atom.xml

# Schema
color: blue

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
#favicon: /favicon.png

# Comments
disqus_shortname:

# Site analytics
google_analytics:
cnzz_analytics:
tencent_analytics:
